baseURL = "https://tapiz.net/"
languageCode = "es-ES"
title = "Proyecto Tapiz"
theme = "docdock"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "tapiz" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter


[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>Más información</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/diacritica/tapiz-web"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Autoría: Pablo Ruiz Múzquiz, Juan de la Cruz"
weight = 30
